name: prettify latexcheatsheet

on:
  push:
    branches:
      - '*' # 'main'
  pull_request:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install prettier
      - run: npx prettier --write index.html
      - name: Setup git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit changes
          git add index.html
          git commit -m "prettify index.html"
          git push
